### ISSUE TITLE
Keep No Maximum limit

### ISSUE THREAD

**Issue by somewhat69** [CruzerBlade9369/NotEnoughGadgets#1]
Sometimes there could be a limit but not for all objects like soldering reels , lights or probably remove mathf.clamp completely or make it a abysmally big number

**Comment by CruzerBlade9369** [comment]
That would create potential lag when there are too many objects existing in the game world. I could add a toggle to increase the maximum limit to the biggest number the game can handle, but it'll have be an optional setting.

**Comment by somewhat69** [comment]
yeah that would be great
